### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by gustavoparedes1978** [DOkwufulueze/eth-vue#9] opened 2017-12-01 21:52 UTC
**Hi, I have already deployed this app to the ganache network on port 7545, but I keep getting the app run on port 3001 even though I have configured truffle.js, I can show the logs:**

_gustavoparedes1978@gustavoparedes1978-HP-Pavilion-g4-Notebook-PC:~/Documents/Cryptocurrencies/soliditytruffleprojects/dapp/truffle boxes/DOkwulueze$ ganache-cli --port 7545
Ganache CLI v6.0.3 (ganache-core: 2.0.2)

Available Accounts
==================
(0) 0x3bc519105fd6ab34b555b62f5d673585744a6c6a
(1) 0xea4e8bab61fa21ef10d4e3bdac32d84b6c66b505
(2) 0x6161bf566473e866a0dea4f4ec111fd199dec664
(3) 0x2ba0ea109e94ee720e635e45c13efcc1f050d7a3
(4) 0x3fa573d569606256a0d8e39a62f667b7eac943c2
(5) 0x96ec7f3b95ced719c601155329913552e97fdef7
(6) 0x08d08a61a9329764f7a1acabf0796478662f9ad0
(7) 0x8067f875d246509b7e1dbf99694745ba0b4b7c6c
(8) 0x5d38bd534cef69b441bbfda679d15aa34b956030
(9) 0x6c213dd255fd207f6ac4bb72f8c363fd50f2b54f

Private Keys
==================
(0) e863a39d52c38ca9c186216ad5f11831ede13b8028f08c842262fc471301344e
(1) a26fea66f7dd62afe381fe36c2fff20fbc189098fc0e3900218f42cbd60b0c67
(2) 63d84623be786797c4f978c4349d3cef8adf714bf407016ef1c48805bb600b41
(3) b80f1d019d04f548fffec15944d17c8afa27ddccecdef6c692e3723d473d8e8f
(4) 3e80247246f53f3454125c60f49309317a79a74c0f1cc495da3613414ba49a1a
(5) 3f4d664e59c42b7e756b9d06c9090b186f60d2ca237e896e2936afdca4ef53cd
(6) 13ca2c633b7e094508e3ac16fb7ebbc7fa34f69bf26c30f0194c5477fa591eca
(7) 85ccd647dca47c7982645b9f6a935b0a167105b654e8a17302b56c1991bfbabf
(8) f53bad5a65b518b6db2ef6f277925577ef9f939a3c6a8f3da44993a136edbeb4
(9) e5ded692b12dfe1805b62fe4f8d81728cf03592fa41647ce5e002aa8cf783908

HD Wallet
==================
Mnemonic:      crater solution correct surprise kite earn try banana vendor lake powder describe
Base HD Path:  m/44'/60'/0'/0/{account_index}

Listening on localhost:7545
net_version
eth_accounts
net_version
net_version
eth_sendTransaction

  Transaction: 0x7a254b7a019bb071c32d31d93eb15295c20003a66df94f5f39fe877e39182566
  Contract created: 0x54850d2da6dae18dbc9992ef389889aa9ffda2e7
  Gas usage: 269607
  Block Number: 1
  Block Time: Fri Dec 01 2017 15:43:49 GMT-0600 (CST)

eth_newBlockFilter
eth_getFilterChanges
eth_getTransactionReceipt
eth_getCode
eth_uninstallFilter
eth_sendTransaction

  Transaction: 0xb45960aaad4c95cb9c60e0d5ce40316fcb58dddef84a34ee488b9b6befb1abc5
  Gas usage: 41981
  Block Number: 2
  Block Time: Fri Dec 01 2017 15:43:50 GMT-0600 (CST)

eth_getTransactionReceipt
eth_accounts
net_version
net_version
eth_sendTransaction

  Transaction: 0x7ecd14b491f5933855527ce9e0b826a456badbe9bc5d45f7a1097d859c5baf47
  Contract created: 0x2aca8bc53a603f13572ccf5d143aaf8b48162534
  Gas usage: 214586
  Block Number: 3
  Block Time: Fri Dec 01 2017 15:43:50 GMT-0600 (CST)

eth_newBlockFilter
eth_getFilterChanges
eth_getTransactionReceipt
eth_getCode
eth_uninstallFilter
net_version
net_version
eth_sendTransaction

  Transaction: 0x67d3d7493c1835fad5815b6900dcb4675e4a8f3cbfddd0b2c9aec6c197976397
  Contract created: 0xd4bce84cdbc4ff1036d2cf97a349c13f6db9ed2d
  Gas usage: 311002
  Block Number: 4
  Block Time: Fri Dec 01 2017 15:43:50 GMT-0600 (CST)

eth_newBlockFilter
eth_getFilterChanges
eth_getTransactionReceipt
eth_getCode
eth_uninstallFilter
net_version
net_version
eth_sendTransaction

  Transaction: 0x400083534a859c763abedc6f2ac8f4935683aa950300fec51f8e32d0fd92c32f
  Contract created: 0x4974d944e5996a2b8d834ba5ce857e0066eb2296
  Gas usage: 950530
  Block Number: 5
  Block Time: Fri Dec 01 2017 15:43:50 GMT-0600 (CST)

eth_newBlockFilter
eth_getFilterChanges
eth_getTransactionReceipt
eth_getCode
eth_uninstallFilter
net_version
net_version
eth_sendTransaction

  Transaction: 0x1de61635038851c3bccc6154a81c305764fe6fe096b9489537faf3ffa0d15cc1
  Contract created: 0x0a6f4c944d298266b040f4d7960d29fd7fb78008
  Gas usage: 68653
  Block Number: 6
  Block Time: Fri Dec 01 2017 15:43:51 GMT-0600 (CST)

eth_newBlockFilter
eth_getFilterChanges
eth_getTransactionReceipt
eth_getCode
eth_uninstallFilter
net_version
net_version
eth_sendTransaction

  Transaction: 0x0ecb23d332e7189c1ffbb19454a8decff5060abd1b2fd679131815a12cef1f48
  Contract created: 0x014e58610dbd1a90d759157f8a98560c943c2f2a
  Gas usage: 215342
  Block Number: 7
  Block Time: Fri Dec 01 2017 15:43:51 GMT-0600 (CST)

eth_newBlockFilter
eth_getFilterChanges
eth_getTransactionReceipt
eth_getCode
eth_uninstallFilter
eth_sendTransaction

  Transaction: 0xc2ad6035a4f5ee5592a721e60212d84d7f8e16e1cba9691a562f6544f8066f59
  Gas usage: 26981
  Block Number: 8
  Block Time: Fri Dec 01 2017 15:43:51 GMT-0600 (CST)

eth_getTransactionReceipt_

**I'm running the dev right here:**

_gustavoparedes1978@gustavoparedes1978-HP-Pavilion-g4-Notebook-PC:~/Documents/Cryptocurrencies/soliditytruffleprojects/dapp/truffle boxes/DOkwufulueze$ npm run d
ev

> eth-vue@4.1.0 dev /home/gustavoparedes1978/Documents/Cryptocurrencies/soliditytruffleprojects/dapp/truffle boxes/DOkwufulueze
> node build/dev-server.js

> Starting dev server...

 DONE  Compiled successfully in 30445ms                                 15:48:20

> Listening at http://localhost:3001_

This is the actual result: 
![image](https://user-images.githubusercontent.com/13125861/33505038-91062ee8-d6af-11e7-89d2-b6e83966711d.png)

**Comment by DOkwufulueze** [comment] 2017-12-02 13:50
Hi, @gustavoparedes1978.

Apologies for the late reply.

This issue occurs when the value of `APPROVED_NETWORK_ID` in `src/util/constants.js is pointing to a network different from that running on your provider. If you're using Metamask, simply create a Custom RPC at `http://localhost:7545` and connect to that on the Metamask provider.

Let me know if this helps.

**Comment by gustavoparedes1978** [comment] 2017-12-04 16:03
Thank you, I will try it later and let you know

**Comment by gustavoparedes1978** [comment] 2017-12-12 17:55
Hi, I have already understtod what I'm doing. Yes I can send a 7545 port request to the EVM through any client, and then I will be deploying the dapp on whatever port I pick. The troublemaker is that I'm not able to plugin with the ganache core browser which seems to be on a beta version and is having a lot of issues currently.

**Comment by DOkwufulueze** [comment] 2017-12-27 16:17
Hi, @gustavoparedes1978, sorry for the late reply. We'll look into the ganache issue you've raised over the weekend and advise appropriately.

**Comment by DOkwufulueze** [comment] 2018-02-14 21:52
Hi, @gustavoparedes1978, the problem may be coming from your ganache installation, as I'm unable to reproduce your issue.

But we'll keep looking into your issue and keep everyone updated in case similar issue is faced by someone else.

**Comment by DOkwufulueze** [comment] 2020-11-08 16:05
Closing as this issue is resolved.

**Closed by DOkwufulueze** 2020-11-08 16:05 UTC
